### ISSUE TITLE
Dev Digest Links Don't Open in iOS App

### ISSUE THREAD

**Issue by rachari** [forem/DEV-ios#242]
**Describe the bug**
I receive the DEV Digest emails which have the links to articles / recent posts. While trying to access one of those links from gmail, it opens the DEV app but does not open the article / link which was present in the email.
 
**To Reproduce**
1. Go to 'DEV Digest (email)'
2. Click on 'Any link present in the email'
3. Link doesn't open in the app

**Expected behavior**
Link should open in the app

**Smartphone (please complete the following information):**
 - Device: iPhone 7 Plus
 - OS: iOS 14.2
- Version: 1.5.0

**Comment by fdoxyz** [comment]
Thank you for the report @rachari! We have a version waiting for Apple review that includes the fix introduced in #237 

I'll close as soon as `1.5.1` is available and we can confirm it fixes the problem

**Comment by fdoxyz** [comment]
`1.5.1` was released earlier today, thank you everyone for the patience. Closing the issue now but if the problem persists after updating feel free to reopen or file a new issue :)
