### ISSUE TITLE
App crashes when I navigate between tabs

### ISSUE THREAD

**Issue by Mangor1no** [forem/DEV-ios#248]
**Describe the bug**
The dev.to app crashes immediately when I navigate between tabs on feed.

**To Reproduce**
1. Go to App Store
2. Download the latest version of dev.to application
3. Open the app
4. Swipe/Tap on the tabs to change the feed. The app crashes on "Month" and "Year" tab.

**Expected behavior**
No crash duh.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS 15.4.1

**Comment by fdocr** [comment]
Hi @Mangor1no, thank you for sharing your report.

[We are sunsetting the DEV apps](https://dev.to/devteam/sunsetting-the-devto-ios-app-44nl), so we're likely not shipping any new updates to them. If you're on the latest version of the DEV app you should be able to see a banner with a link to help you install the Forem app instead.

They're both built with [the same components](https://github.com/forem/ForemWebView-ios/) under the hood though. You might not have this problem on the Forem app, but if you do, I'd love to hear from you to investigate further. I can't replicate this issue on version `1.4.4` but I am on iOS `15.5`.

Feel free to reply back here or open a new issue on the [forem/forem repo](https://github.com/forem/forem) if you do continue to experience this.
