### ISSUE TITLE
Add steps on how to install the app on a physical iOS device

### ISSUE THREAD

**Issue by princefishthrower** [forem/DEV-ios#50]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but a request to include steps on how to install the beta app on an actual device as opposed to in the macOS Simulator App. 

Its been a long while since I've done any native development, and I had to relearn all the quirks of allowing a development stage app to be installed on my iPhone. I think this will be the case in the future if there are more people coming in from DEV.to to check out and install the app (like me 😜). I'd be happy to do this as a pull request for Hacktoberfest, if it's deemed a good idea! (This may become moot if everything is moved to TestFlight)

**Describe the solution you'd like**
A step by step guide in the README on how to get the app working on a physical device. (Not too bloated, links to the "gotchya" steps that have already been documented many many times on StackOverflow and similar)

**Describe alternatives you've considered**
This could be put somewhere else in the repository, but I think in the README makes the most sense.

**Additional context**
N/A

**Comment by jessleenyc** [comment]
@frewinchristopher this makes sense. Do you want to draft up language for the readme in a PR?

**Comment by chickdan** [comment]
> This may become moot if everything is moved to TestFlight

Is this now moot considering the app is now on TestFlight?

**Comment by jessleenyc** [comment]
Well, the _latest changes_ aren't on TestFlight. I thought this was more for folks who are new to iOS development and wanted to give it a go. Perhaps I misunderstood! @frewinchristopher feel free to close if that's the case.

**Comment by chickdan** [comment]
I wasn't sure either but saw that bit so I thought I'd ask!

**Comment by frewinchristopher** [comment]
I yield to the owners of the repository! 😄 

If we want this repo to be friendly to folks who want to get started with iOS development, then I think it makes sense to include some steps and common gotchas.

I _do_ have a lot of screenshots and a few helpful links that I could include. I'd be happy to draft it in the README as a way to giving back to the DEV.to community :)

Let me know!

**Comment by jessleenyc** [comment]
@frewinchristopher definitely on board to make this repo as friendly as possible. Feel free to submit a PR!

**Comment by frewinchristopher** [comment]
Alright, I'm on it!

**Comment by ethanellan** [comment]
Thank you for providing the steps to fix it, but can you please provide me with an instant help for **[AOL Hacked Account](http://www.aolhelp247.com/recover-aol-hacked-account/)** As I have tried all the techniques here by calling on toll-free number technical support number of AOL email **+1(866)257-5356**

**Comment by larson-carter** [comment]
Is there any update on this? Should this issue be closed as it is over 2 years old. Also it is irrelevant now days?

**Comment by fdoxyz** [comment]
I agree, the README has the [contributing](https://github.com/forem/DEV-ios#contributing) instructions to get started (and PRs to improve it are always welcome) and [this SO answer](https://stackoverflow.com/a/4952845/3462026) can help anyone that lands here.
